# Generated by Django 4.2.3 on 2024-07-04 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads')),
                ('description', models.TextField(max_length=500, null='False')),
                ('status', models.BooleanField(default=False, help_text='0-show,1-hidden')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads')),
                ('quantity', models.IntegerField()),
                ('old_price', models.FloatField()),
                ('new_price', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-hidden')),
                ('trend', models.BooleanField(default=False, help_text='0-default,0-trend')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.catagory')),
            ],
        ),
    ]
